### ISSUE TITLE
Erreur de compilation avec le Makefile

### ISSUE THREAD

**Issue by maxime-killinger** [motet-a/liblapin-tutorial#10]
Chez moi, la compilation avec le make file ne fonctionne qu'avec cette ligne.
                  -I/home/${USER}/.froot/include/

**Comment by motet-a** [comment]
Salut,

Est-ce que ta variable d’environnement `$C_INCLUDE_PATH` est correcte ? 
Que vois-tu si tu fais : 

``` sh
$ echo $C_INCLUDE_PATH
```

Normalement, [la page sur l’installation](http://liblapin.readthedocs.org/fr/latest/install.html#installation-avec-fake-install-sh-recommande) est correcte.

**Comment by maxime-killinger** [comment]
Effectivement je n'ai rien que je l'affiche, pourtant je pense que ma ligne est bonne dans le fish.config, je regarderai ça, merci.
